# permissions for end users to view fetchdata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fetchdata-viewer-role
rules:
- apiGroups:
  - my.domain
  resources:
  - fetchdata
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - my.domain
  resources:
  - fetchdata/status
  verbs:
  - get
