apiVersion: my.domain/v1alpha1
kind: Fetchdata
metadata:
  name: fetchdata-cronjob
spec:
  # Add fields here
  cronjobNamespace: koku-metrics-operator
  schedule: 0 */6 * * *
  backupSrc: /tmp/koku-metrics-operator-data/upload
  unzipDir: /tmp/koku-metrics-operator-data/s3sync
